set_debug bug
In cases where debug is not assigned we error with 

'NoneType' object has no attribute 'upper': AttributeError
Traceback (most recent call last):
File "/var/task/lambda_function.py", line 15, in lambda_handler
redshift_monitoring.monitor_cluster(config_sources)
File "/var/task/redshift_monitoring.py", line 298, in monitor_cluster
if get_config_value(['DEBUG', 'debug', ], config_sources).upper() == 'TRUE':
AttributeError: 'NoneType' object has no attribute 'upper'

This patch only attempts to check the string value of the debug config value in cases where it is defined, so as to avoid the UPPER call on a NoneType.